### ISSUE TITLE
Create `baseline_smear_grade` variable

### ISSUE THREAD

**Issue by JayAchar** [JayAchar/tbmstr#42]

**Comment by D1ZER99** [comment]
Hi, Jay, check this one please

```#### Approach to keep only first sputum culture result (of second in case the first is 9 (Unknown)
library(tidyverse)

# Let's assume that data frame with results is called "myc"

myc_clean <- myc %>% 
  arrange(globalrecordid, datespecimen) # sort by ID and date of speicement collection

myc_clean <- myc_clean %>% 
  mutate(test_order = row_number())     # give each row test number

unknown_rows <- myc_clean$result == 9   ##
myc_clean$result[unknown_rows] <- NA    ## assign 9 ("Unknown") as NA

myc_clean <- myc_clean %>% 
  fill(result, .direction = "down")     # fill all NA with the result above ()

myc_clean <- myc_clean  %>% 
  group_by(globalrecordid) %>% 
  slice(1)                              # grouping by ID and the select only the first row

myc_clean <- myc_clean %>% 
  ungroup() %>% 
  select(globalrecordid, datespecimen, month0, result)                  # ungrouping and unselect "test_order"
```

The result is a pretty clean data frame, almost every result is from month0 or month1. So probably that might be a solution

**Comment by JayAchar** [comment]
Thanks! 

I'm going to incorporate this into a function within the package, so can't really include the tidyverse as a dependency. You'll see that creating your own functions with `tidyverse` functions inside can be difficult - try running the following:

```
custom_filter <- function(df, var) {
  df |> 
    dplyr::filter(var > 5)
}

df <- data.frame(
  x = 1:10
)

custom_filter(df = df, var = "x")
```

Also, I think we need to add some logic to think about how specimen collection relates to treatment initiation - i.e. the baseline specimen should be before treatment start, but maybe not too far in the past.

Thanks again for sharing - I'll try and draft somehting in the next 1-2 days.
